import { NextRequest, NextResponse } from "next/server"

import { createAdminClient } from "@/lib/supabase/admin"
import { sendEmail } from "@/lib/emails/send"

function cronAuth(req: NextRequest) {
  return (
    req.headers.get("x-cron-secret") ??
    req.headers.get("authorization")?.replace("Bearer ", "") ??
    null
  )
}

function yesterday() {
  const d = new Date()
  d.setUTCDate(d.getUTCDate() - 1)
  return d.toISOString().slice(0, 10)
}

function isMonday() { return new Date().getUTCDay() === 1 }
function fmt(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n)
}

async function sendWeeklyReport(admin: ReturnType<typeof createAdminClient>) {
  const today = new Date()
  const sevenDaysAgo = new Date(today)
  sevenDaysAgo.setUTCDate(sevenDaysAgo.getUTCDate() - 7)
  const fourteenDaysAgo = new Date(today)
  fourteenDaysAgo.setUTCDate(fourteenDaysAgo.getUTCDate() - 14)

  const { data: thisWeek } = await admin
    .from("finance_snapshots")
    .select("*")
    .gte("snapshot_date", sevenDaysAgo.toISOString().slice(0, 10))
    .lt("snapshot_date", today.toISOString().slice(0, 10))

  const { data: lastWeek } = await admin
    .from("finance_snapshots")
    .select("*")
    .gte("snapshot_date", fourteenDaysAgo.toISOString().slice(0, 10))
    .lt("snapshot_date", sevenDaysAgo.toISOString().slice(0, 10))

  const sumField = (rows: typeof thisWeek, field: string) =>
    (rows ?? []).reduce((s, r) => s + Number((r as Record<string, unknown>)[field] ?? 0), 0)

  const twRevenue = sumField(thisWeek, "net_platform_revenue")
  const lwRevenue = sumField(lastWeek, "net_platform_revenue")
  const twGross = sumField(thisWeek, "gross_booking_value")
  const lwGross = sumField(lastWeek, "gross_booking_value")
  const twBookings = sumField(thisWeek, "booking_count")
  const twUsers = sumField(thisWeek, "new_users")
  const revChange = lwRevenue > 0 ? ((twRevenue - lwRevenue) / lwRevenue * 100).toFixed(1) : "N/A"
  const monthlyRunRate = twRevenue * 4.33
  const fixedCosts = 7 // Redis ~$7/mo
  const coversCosts = monthlyRunRate >= fixedCosts

  const html = `<div style="font-family:system-ui,Arial,sans-serif;max-width:600px;color:#1A1410;padding:24px">
<h2 style="margin:0 0 4px">thrml Weekly Finance</h2>
<p style="margin:0 0 20px;color:#796A5E;font-size:13px">Week ending ${today.toISOString().slice(0, 10)}</p>

<table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:20px">
<tr style="background:#F5F0EA"><th style="padding:8px;text-align:left">Metric</th><th style="padding:8px;text-align:right">This Week</th><th style="padding:8px;text-align:right">Last Week</th></tr>
<tr><td style="padding:8px;border-top:1px solid #EDE8E2">Gross Booking Value</td><td style="padding:8px;text-align:right;border-top:1px solid #EDE8E2">${fmt(twGross)}</td><td style="padding:8px;text-align:right;border-top:1px solid #EDE8E2">${fmt(lwGross)}</td></tr>
<tr style="background:#FCFAF7"><td style="padding:8px">Platform Revenue (net)</td><td style="padding:8px;text-align:right">${fmt(twRevenue)}</td><td style="padding:8px;text-align:right">${fmt(lwRevenue)}</td></tr>
<tr><td style="padding:8px;border-top:1px solid #EDE8E2">Bookings</td><td style="padding:8px;text-align:right;border-top:1px solid #EDE8E2">${twBookings}</td><td style="padding:8px;text-align:right;border-top:1px solid #EDE8E2">—</td></tr>
<tr style="background:#FCFAF7"><td style="padding:8px">New Users</td><td style="padding:8px;text-align:right">${twUsers}</td><td style="padding:8px;text-align:right">—</td></tr>
</table>

<div style="background:#F5F0EA;padding:12px 16px;border-radius:8px;margin-bottom:16px;font-size:14px">
<strong>Monthly Run Rate:</strong> ${fmt(monthlyRunRate)} &nbsp;·&nbsp;
<strong>vs Fixed Costs ($${fixedCosts}/mo):</strong> ${coversCosts ? "✅ Covered" : "⚠️ Not yet"} &nbsp;·&nbsp;
<strong>Revenue Trend:</strong> ${revChange}%
</div>

<p style="font-size:12px;color:#796A5E;margin-top:24px">thrml · auto-generated by finance agent · <a href="https://usethrml.com/admin" style="color:#C4623A">Admin Dashboard</a></p>
</div>`

  await sendEmail({
    to: "etter.dom@gmail.com",
    subject: `thrml Weekly Finance — ${fmt(twRevenue)} net revenue`,
    html,
    text: `thrml Weekly Finance\nNet revenue: ${fmt(twRevenue)} (${revChange}% vs last week)\nGross: ${fmt(twGross)} · Bookings: ${twBookings} · New users: ${twUsers}\nRun rate: ${fmt(monthlyRunRate)}/mo`,
  })
}

export async function GET(req: NextRequest) {
  if (!process.env.CRON_SECRET || cronAuth(req) !== process.env.CRON_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const admin = createAdminClient()
  const runStart = Date.now()
  const { data: runRow } = await admin
    .from("agent_runs")
    .insert({ agent_name: "finance", status: "running" })
    .select("id").single()
  const runId = runRow?.id ?? null

  try {
    const date = yesterday()
    const dayStart = `${date}T00:00:00.000Z`
    const dayEnd = `${date}T23:59:59.999Z`

    const { data: bookings } = await admin
      .from("bookings")
      .select("total_charged, service_fee, host_payout, refund_amount, status")
      .in("status", ["confirmed", "completed"])
      .gte("created_at", dayStart)
      .lte("created_at", dayEnd)

    const rows = bookings ?? []
    const bookingCount = rows.length
    const grossBookingValue = rows.reduce((s, r) => s + Number(r.total_charged ?? 0), 0)
    const platformRevenue = rows.reduce((s, r) => s + Number(r.service_fee ?? 0), 0)
    const hostPayouts = rows.reduce((s, r) => s + Number(r.host_payout ?? 0), 0)
    const refundsIssued = rows.reduce((s, r) => s + Number(r.refund_amount ?? 0), 0)
    const netPlatformRevenue = platformRevenue - refundsIssued
    const avgOrderValue = bookingCount > 0 ? grossBookingValue / bookingCount : 0

    const { count: newUsers } = await admin.from("profiles")
      .select("id", { count: "exact", head: true })
      .gte("created_at", dayStart).lte("created_at", dayEnd)

    const { count: newListings } = await admin.from("listings")
      .select("id", { count: "exact", head: true })
      .gte("created_at", dayStart).lte("created_at", dayEnd)

    await admin.from("finance_snapshots").upsert({
      snapshot_date: date,
      booking_count: bookingCount,
      gross_booking_value: grossBookingValue,
      platform_revenue: platformRevenue,
      host_payouts: hostPayouts,
      refunds_issued: refundsIssued,
      net_platform_revenue: netPlatformRevenue,
      avg_order_value: avgOrderValue,
      new_users: newUsers ?? 0,
      new_listings: newListings ?? 0,
    }, { onConflict: "snapshot_date" })

    // Anomaly: high refund rate
    const refundRate = grossBookingValue > 0 ? refundsIssued / grossBookingValue : 0
    if (refundRate > 0.2) {
      await admin.from("ops_alerts").insert({
        severity: "WARNING", category: "finance",
        message: `High refund rate: ${(refundRate * 100).toFixed(1)}% of daily revenue`,
        details: { date, refundsIssued, grossBookingValue },
      })
    }

    if (isMonday()) { await sendWeeklyReport(admin) }

    const results = { date, bookingCount, grossBookingValue, platformRevenue, netPlatformRevenue, newUsers, newListings }
    if (runId) await admin.from("agent_runs").update({
      status: "success", completed_at: new Date().toISOString(),
      duration_ms: Date.now() - runStart, results,
    }).eq("id", runId)

    return NextResponse.json({ ok: true, ...results })
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Unknown error"
    if (runId) await admin.from("agent_runs").update({
      status: "error", completed_at: new Date().toISOString(),
      duration_ms: Date.now() - runStart, error_message: msg,
    }).eq("id", runId)
    return NextResponse.json({ ok: false, error: msg }, { status: 500 })
  }
}
