import { NextRequest, NextResponse } from "next/server"

import {
  upsertDailyFinanceSnapshot,
} from "@/lib/finance/snapshot-builder"
import { renderThrmlEmail } from "@/lib/emails/render-layout"
import { sendEmail } from "@/lib/emails/send"
import { createAdminClient } from "@/lib/supabase/admin"

function cronAuth(req: NextRequest) {
  return (
    req.headers.get("x-cron-secret") ??
    req.headers.get("authorization")?.replace("Bearer ", "") ??
    null
  )
}

function yesterday() {
  const d = new Date()
  d.setUTCDate(d.getUTCDate() - 1)
  return d.toISOString().slice(0, 10)
}

function isMonday() {
  return new Date().getUTCDay() === 1
}

function fmt(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n)
}

async function sendWeeklyReport(admin: ReturnType<typeof createAdminClient>) {
  const today = new Date()
  const sevenDaysAgo = new Date(today)
  sevenDaysAgo.setUTCDate(sevenDaysAgo.getUTCDate() - 7)
  const fourteenDaysAgo = new Date(today)
  fourteenDaysAgo.setUTCDate(fourteenDaysAgo.getUTCDate() - 14)

  const { data: thisWeek } = await admin
    .from("finance_snapshots")
    .select("*")
    .gte("snapshot_date", sevenDaysAgo.toISOString().slice(0, 10))
    .lt("snapshot_date", today.toISOString().slice(0, 10))

  const { data: lastWeek } = await admin
    .from("finance_snapshots")
    .select("*")
    .gte("snapshot_date", fourteenDaysAgo.toISOString().slice(0, 10))
    .lt("snapshot_date", sevenDaysAgo.toISOString().slice(0, 10))

  const sumField = (rows: typeof thisWeek, field: string) =>
    (rows ?? []).reduce((s, r) => s + Number((r as Record<string, unknown>)[field] ?? 0), 0)

  const twRevenue = sumField(thisWeek, "net_platform_revenue")
  const lwRevenue = sumField(lastWeek, "net_platform_revenue")
  const twGross = sumField(thisWeek, "gross_booking_value")
  const lwGross = sumField(lastWeek, "gross_booking_value")
  const twBookings = sumField(thisWeek, "booking_count")
  const twUsers = sumField(thisWeek, "new_users")
  const twRefunds = sumField(thisWeek, "refunds_issued")
  const twCredits = sumField(thisWeek, "credits_applied")
  const revChange = lwRevenue > 0 ? ((twRevenue - lwRevenue) / lwRevenue * 100).toFixed(1) : "N/A"
  const monthlyRunRate = twRevenue * 4.33
  const fixedCosts = 7
  const coversCosts = monthlyRunRate >= fixedCosts

  const financeContentHtml = `
<p style="margin:0 0 20px;color:#796A5E;font-size:13px">Week ending ${today.toISOString().slice(0, 10)}</p>
<table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:20px">
<tr style="background:#F5F0EA"><th style="padding:8px;text-align:left">Metric</th><th style="padding:8px;text-align:right">This Week</th><th style="padding:8px;text-align:right">Last Week</th></tr>
<tr><td style="padding:8px;border-top:1px solid #EDE8E2">Gross Booking Value</td><td style="padding:8px;text-align:right;border-top:1px solid #EDE8E2">${fmt(twGross)}</td><td style="padding:8px;text-align:right;border-top:1px solid #EDE8E2">${fmt(lwGross)}</td></tr>
<tr style="background:#FCFAF7"><td style="padding:8px">Platform Revenue (net)</td><td style="padding:8px;text-align:right">${fmt(twRevenue)}</td><td style="padding:8px;text-align:right">${fmt(lwRevenue)}</td></tr>
<tr><td style="padding:8px;border-top:1px solid #EDE8E2">Refunds</td><td style="padding:8px;text-align:right;border-top:1px solid #EDE8E2">${fmt(twRefunds)}</td><td style="padding:8px;text-align:right;border-top:1px solid #EDE8E2">${fmt(sumField(lastWeek, "refunds_issued"))}</td></tr>
<tr style="background:#FCFAF7"><td style="padding:8px">Promo credits applied</td><td style="padding:8px;text-align:right">${fmt(twCredits)}</td><td style="padding:8px;text-align:right">${fmt(sumField(lastWeek, "credits_applied"))}</td></tr>
<tr><td style="padding:8px;border-top:1px solid #EDE8E2">Bookings</td><td style="padding:8px;text-align:right;border-top:1px solid #EDE8E2">${twBookings}</td><td style="padding:8px;text-align:right;border-top:1px solid #EDE8E2">—</td></tr>
<tr style="background:#FCFAF7"><td style="padding:8px">New Users</td><td style="padding:8px;text-align:right">${twUsers}</td><td style="padding:8px;text-align:right">—</td></tr>
</table>

<div style="background:#F5F0EA;padding:12px 16px;border-radius:8px;margin-bottom:16px;font-size:14px">
<strong>Monthly Run Rate:</strong> ${fmt(monthlyRunRate)} &nbsp;·&nbsp;
<strong>vs Fixed Costs ($${fixedCosts}/mo):</strong> ${coversCosts ? "✅ Covered" : "⚠️ Not yet"} &nbsp;·&nbsp;
<strong>Revenue Trend:</strong> ${revChange}%
</div>
`

  const appUrl = process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "") ?? "https://usethrml.com"
  const html = await renderThrmlEmail({
    preview: `thrml Weekly Finance — ${fmt(twRevenue)}`,
    kicker: "Admin",
    title: "thrml Weekly Finance",
    contentHtml: financeContentHtml,
    cta: { label: "Admin Dashboard", href: `${appUrl}/admin` },
    footnote: "thrml · auto-generated by finance agent",
  })

  await sendEmail({
    to: "etter.dom@gmail.com",
    subject: `thrml Weekly Finance — ${fmt(twRevenue)} net revenue`,
    html,
    text: `thrml Weekly Finance\nNet revenue: ${fmt(twRevenue)} (${revChange}% vs last week)\nGross: ${fmt(twGross)} · Refunds: ${fmt(twRefunds)} · Credits: ${fmt(twCredits)}\nBookings: ${twBookings} · New users: ${twUsers}\nRun rate: ${fmt(monthlyRunRate)}/mo`,
  })
}

export async function GET(req: NextRequest) {
  if (!process.env.CRON_SECRET || cronAuth(req) !== process.env.CRON_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const admin = createAdminClient()
  const runStart = Date.now()
  const { data: runRow } = await admin
    .from("agent_runs")
    .insert({ agent_name: "finance", status: "running" })
    .select("id")
    .single()
  const runId = runRow?.id ?? null

  try {
    const date = yesterday()
    const snapshot = await upsertDailyFinanceSnapshot(admin, date)

    const refundRate =
      snapshot.gross_booking_value > 0
        ? snapshot.refunds_issued / snapshot.gross_booking_value
        : 0
    if (refundRate > 0.2) {
      await admin.from("ops_alerts").insert({
        severity: "WARNING",
        category: "finance",
        message: `High refund rate: ${(refundRate * 100).toFixed(1)}% of daily GBV`,
        details: {
          date,
          refundsIssued: snapshot.refunds_issued,
          grossBookingValue: snapshot.gross_booking_value,
        },
      })
    }

    if (isMonday()) {
      await sendWeeklyReport(admin)
    }

    const results = {
      date,
      bookingCount: snapshot.booking_count,
      grossBookingValue: snapshot.gross_booking_value,
      grossPlatformTake: snapshot.gross_platform_take,
      platformRevenue: snapshot.platform_revenue,
      refundsIssued: snapshot.refunds_issued,
      creditsApplied: snapshot.credits_applied,
      chargebacks: snapshot.chargebacks,
      netPlatformRevenue: snapshot.net_platform_revenue,
      newUsers: snapshot.new_users,
      newListings: snapshot.new_listings,
    }
    if (runId) {
      await admin
        .from("agent_runs")
        .update({
          status: "success",
          completed_at: new Date().toISOString(),
          duration_ms: Date.now() - runStart,
          results,
        })
        .eq("id", runId)
    }

    return NextResponse.json({ ok: true, ...results })
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Unknown error"
    if (runId) {
      await admin
        .from("agent_runs")
        .update({
          status: "error",
          completed_at: new Date().toISOString(),
          duration_ms: Date.now() - runStart,
          error_message: msg,
        })
        .eq("id", runId)
    }
    return NextResponse.json({ ok: false, error: msg }, { status: 500 })
  }
}
