export const AMENITIES_BY_SERVICE_TYPE: Record<string, string[]> = {
  sauna: [
    "Towels provided",
    "Robe provided",
    "Cold shower",
    "Cold outdoor shower",
    "Outdoor shower",
    "Shower access",
    "Parking",
    "Birch whisk (vihta)",
    "Eucalyptus steam",
    "Outdoor deck",
    "Fire pit",
    "String lights",
    "Covered shelter",
    "Changing room",
    "Private room",
    "Ocean views",
    "Canyon views",
    "Reservoir views",
    "Herbal tea",
    "Self-serve",
    "Access code provided",
    "Timer provided",
    "Temperature gauge visible",
  ],
  cold_plunge: [
    "Towels provided",
    "Warm shower post-plunge",
    "Outdoor shower",
    "Shower access",
    "Parking",
    "Steps/ladder access",
    "Covered shelter",
    "Outdoor deck",
    "Timer provided",
    "Temperature gauge visible",
    "Protocol guide provided",
    "Changing room",
    "Private room",
    "Ocean views",
    "Canyon views",
    "Self-serve",
    "Access code provided",
    "Herbal tea",
    "Zero gravity chairs",
  ],
  contrast_therapy: [
    "Towels provided",
    "Robe provided",
    "Shower access",
    "Outdoor shower",
    "Parking",
    "Steps/ladder access",
    "Covered shelter",
    "Outdoor deck",
    "Timer provided",
    "Temperature gauge visible",
    "Protocol guide provided",
    "Changing room",
    "Private room",
    "Herbal tea",
    "Self-serve",
    "Access code provided",
    "Ocean views",
    "Canyon views",
  ],
  infrared_light: [
    "Towels provided",
    "Robe provided",
    "Shower access",
    "Parking",
    "Eye protection provided",
    "Changing room",
    "Private room",
    "Chromotherapy",
    "Light therapy option",
    "Bluetooth audio",
    "Self-serve",
    "Access code provided",
    "Timer provided",
    "Zero gravity chairs",
  ],
  float_tank: [
    "Towels provided",
    "Robe provided",
    "Shower (pre & post)",
    "Parking",
    "Earplugs provided",
    "Private room",
    "Quiet/no talking",
    "Quiet space",
    "Journaling space",
    "Post-float tea",
    "Bluetooth audio",
    "Changing room",
    "Access code provided",
    "Self-serve",
  ],
  hyperbaric: [
    "Towels provided",
    "Parking",
    "Private room",
    "Attendant on-site",
    "Medical clearance required",
    "Soft shell chamber",
    "WiFi inside chamber",
    "Bluetooth audio",
    "Changing room",
    "Access code provided",
    "Recliner/bed provided",
  ],
  pemf: [
    "Towels provided",
    "Parking",
    "Private room",
    "Full body mat",
    "Recliner/bed provided",
    "Quiet space",
    "Self-serve",
    "Access code provided",
    "Changing room",
  ],
  halotherapy: [
    "Towels provided",
    "Parking",
    "Private room",
    "Dry salt room",
    "Salt cave aesthetic",
    "Quiet space",
    "Chromotherapy",
    "Zero gravity chairs",
    "Self-serve",
    "Access code provided",
    "Changing room",
    "Timer provided",
  ],
  general: [
    "Towels provided",
    "Parking",
    "Private room",
    "Shower access",
    "Changing room",
    "Self-serve",
    "Access code provided",
    "Timer provided",
  ],
}
