-- Creative generation pipeline: briefs generated by agents and their output assets.

create table if not exists public.creative_briefs (
  id uuid primary key default gen_random_uuid(),
  trigger_type text,
  trigger_data jsonb,
  status text default 'pending',
  hook text,
  format text,
  visual_direction text,
  copy_primary text,
  copy_headline text,
  cta text,
  target_audience text,
  reference_image_urls text[],
  rationale text,
  created_at timestamptz default now(),
  approved_at timestamptz,
  created_by text default 'agent'
);

create table if not exists public.creative_assets (
  id uuid primary key default gen_random_uuid(),
  brief_id uuid references public.creative_briefs(id),
  asset_type text,
  generation_tool text,
  gcs_url text,
  gcs_path text,
  meta_video_id text,
  meta_ad_id text,
  meta_adset_id text,
  status text default 'generated',
  performance_data jsonb,
  variation_index int,
  created_at timestamptz default now(),
  approved_at timestamptz,
  launched_at timestamptz
);

alter table public.creative_queue
  add column if not exists type text,
  add column if not exists brief_id uuid references public.creative_briefs(id);

alter table public.creative_briefs enable row level security;
alter table public.creative_assets enable row level security;

drop policy if exists creative_briefs_service_role_all on public.creative_briefs;
create policy creative_briefs_service_role_all
on public.creative_briefs
for all
to service_role
using (true)
with check (true);

drop policy if exists creative_assets_service_role_all on public.creative_assets;
create policy creative_assets_service_role_all
on public.creative_assets
for all
to service_role
using (true)
with check (true);

grant select, insert, update, delete on public.creative_briefs to service_role;
grant select, insert, update, delete on public.creative_assets to service_role;
